components_manager:

  components:

    server:
      listener:
        port: 8083
        task_processor: main-task-processor

    logging:
      loggers:
        default:
          file_path: '@stderr'
          level: debug
          overflow_behavior: discard

    handler-link-maker:
        path: /v1/create
        task_processor: main-task-processor
        method: GET,POST

    handler-redirect-to-long:
      path: /v1/link/{id}
      task_processor: main-task-processor
      method: GET,POST

    recent-links-cache:
      update-types: full-and-incremental
      full-update-interval: 1h
      update-interval: 5s

    postgres-db-1:
      # dbconnection: "postgresql://testsuite@localhost:15433/mydb_db_1"
      dbconnection: "postgresql://user:password@servicepostgres:5432/mydb"
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: false
      connlimit_mode: manual
      connecting_limit: 100

    testsuite-support: {}

    tests-control:
      load-enabled: true # false
      path: /tests/{action}
      method: GET,POST
      task_processor: main-task-processor
      testpoint-timeout: 10s
      testpoint-url: mockserver/testpoint
      throttling_enabled: false

    http-client:
      core-component: http-client-core

    http-client-middleware-pipeline: {} # for tests
    
    http-client-core:
      fs-task-processor: fs-task-processor
      testsuite-enabled: true

    dns-client:
      fs-task-processor: fs-task-processor

    dynamic-config:
      defaults:
        HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
        POSTGRES_DEFAULT_COMMAND_CONTROL:
          network_timeout_ms: 750
          statement_timeout_ms: 500
        POSTGRES_QUERIES_COMMAND_CONTROL:
          sample_select_value:
            network_timeout_ms: 70
            statement_timeout_ms: 40
          sample_transaction_insert_key_value:
            network_timeout_ms: 200
            statement_timeout_ms: 150

  task_processors:

    main-task-processor:
      worker_threads: 4

    fs-task-processor:
      worker_threads: 4

  default_task_processor: main-task-processor